url: https://www.loudas.com
baseurl: /
plugins: 
    - jekyll-paginate
    - jekyll-feed
    - jekyll-archives
site_name: "The life and times of Paul Willard"
description: "Just another internet addict"
thumbnails: "/assets/images/posts/thumbnails/"
post-images: "/assets/images/posts/"
timezone: Pacific/Auckland
sass:
    load_paths:
        - _sass
        - node_modules
        - assets/css
        - assets/vendor
    style: compressed
exclude: [node_modules, Gemfile, package.json, package-lock.json, .gitignore, README.md, ctl.sh, static_prototype, mogrify_images_to_400px_wide.sh]
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      author: "paul"
  - scope:
      path: ""
    values:
      layout: "default"
collections:
    authors:
        type: "authors"
        layout: "author"
        output: true
paginate: 5
assets:
  compress:
    css:  sass
    js:   uglifier
repository: "TerminalAddict/loudas.com"
staticman:
    branch: "master"
jekyll-archives:
  enabled: []
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
